version: "3.8"

services:
  postgres:
    image: "${POSTGRES_IMAGE}"
    container_name: cabin-postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - "${POSTGRES_DATA_PATH}:/var/lib/postgresql/data"
    networks:
      - internal

  nginx-proxy:
    image: "${NGINX_IMAGE}"
    container_name: cabin-nginx-proxy
    # Proxy only—Postgres stays hidden
    ports:
      - "${NGINX_PORT}:5432"
    volumes:
      - "${NGINX_CONFIG_PATH}:/etc/nginx/nginx.conf:ro"
    depends_on:
      - postgres
    networks:
      - internal

  pgadmin:
    image: "${PGADMIN_IMAGE}"
    container_name: cabin-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      - internal

  rabbitmq:
    image: "${RABBITMQ_IMAGE}"
    container_name: cabin-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MANAGEMENT_PORT}:15672"
    networks:
      - internal

networks:
  internal:
    external: true
    name: "${NETWORK_NAME}"
